# Numpy
- Numpy library contains a multi-dimentional array and matrix data structures.
- It aims to provide an array object that is upto 50x faster that traditional Python lists.
- The array object in Numpy is called **ndarray**.

### Why is Numpy faster than lists?
- Numpy arrays are stored ar one continuous place in memory unlike lists, so processes can access manipulate them very efficiently.
- This behavior is called locality of reference in computer science.
- This is the main reason why Numpy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Import numpy

In [1]:
import numpy as np

### Creating numpy array

In [2]:
ar1 = np.array([1,2,3,4,5]) # input as list
print(ar1)
print(type(ar1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
ar2 = np.array((1,2,3,4,5)) # input as tuple
print(ar2)
print(type(ar2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimesions in array

In [4]:
ar3 = np.array(20)
print(ar3)
print(ar3.ndim)

20
0


### Find array Dimension

In [5]:
ar4 = np.array([1,2,3,4,5])
print(ar4)
print(ar4.ndim)

[1 2 3 4 5]
1


In [6]:
ar5 = np.array([[1,2,3],[4,5,6]])
print(ar5)
print(ar5.ndim)

[[1 2 3]
 [4 5 6]]
2


In [7]:
ar6 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ar6)
print(ar5.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
2


### Higher dimensional arrays
- An array can have any number of dimensions.
- When the array is created, you can define the number of dimensions by using the **ndim** argument

### Creating an array with 5 dimensions and verify it has 5 dimensions

In [8]:
arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print("Number of dimensions: ",arr.ndim)

[[[[[1 2 3 4]]]]]
Number of dimensions:  5


### Slicing of numpy array

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])
print(arr[1::2])

[2 3 4 5]
[2 4 6 8]


### Data types in NumPy
Numpy has some extra data types and refer to data types with one character
- i : integer
- b : boolean
- u : unsigned integer
- f : float
- c : complex float
- m : timedelta
- M : datetime
- O : object
- S : string
- U : unicode string
- V : fixed chunk of memory for other type (void)

In [10]:
arr = np.array([1,2,3,4,5,6])
print(arr.dtype)

int32


In [11]:
arr2 = np.array([1,2,3,4],dtype='S')
print(arr2)
print(arr2.dtype)

[b'1' b'2' b'3' b'4']
|S1


### Array shape
- the shape of an array is the number of elements in each dimension

In [12]:
ar1 = np.array([[1,2,3,4],[5,6,7,8]])
print(ar1)
print(ar1.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [13]:
ar2 = np.array([[[1,2,3,4],[5,6,7,8],[10,20,30,40]]])
print(ar2)
print(ar2.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [10 20 30 40]]]
(1, 3, 4)


### Joining numpy arrays

In [14]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


### Join 2D array

In [15]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[10,20,30],[40,50,60]])

arr = np.concatenate((arr3,arr4),axis=1) # row wise
print(arr)

[[ 1  2  3 10 20 30]
 [ 4  5  6 40 50 60]]


In [16]:
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[10,20,30],[40,50,60]])

arr = np.concatenate((arr3,arr4),axis=0) # column wise
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]


### Spliting numpy arrays

In [17]:
arr = np.array([1,2,3,4,5,6])
newArr = np.array_split(arr,3)
print(newArr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
arr = np.array([1,2,3,4,5,6])
newArr = np.array_split(arr,4)
print(newArr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### ravel() & flatten() function
- It converts multi-dimensional arrays into 1D array

| **ravel()**     | **flatten()**      |
| ------------- | ------------- |
| Return only reference/view of the original array | Return copy of the original array |
| If you modify the array you would notice that the value of the original array also changes. | If you modify any value of this array value of the original array is not affected. |
| Ravel is faster than flatten() as it does not occupy any memory. | Flatten() is comparatively slower than ravel() as it occupies memory. |
| Ravel is a library-level function.  | Flatten is a method of an ndarray object. Let us check out the difference in this code. |

In [19]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is: ",m.ndim)

n = m.ravel()
print(n)
print("dimension is: ",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is:  3
[1 2 3 4 5 6 7 8 9]
dimension is:  1


In [20]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension is: ",m.ndim)

n = m.flatten()
print(n)
print("dimension is: ",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension is:  3
[1 2 3 4 5 6 7 8 9]
dimension is:  1


### unique() function

In [21]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)

x = np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


In [26]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
print()
x = np.unique(k, return_index=True, return_counts=True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10], dtype=int64), array([2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1], dtype=int64))


### delete() function

In [27]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(a)
print()
print(d)

[12 13 14 15]

[12 14 15]


In [28]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)
m = np.delete(x,1,axis=0)
print()
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]
